# Generated by Django 3.2.9 on 2021-11-14 16:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=100)),
                ('sub_time', models.TimeField()),
                ('sub_name', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=100)),
                ('st_group', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('au_number', models.CharField(max_length=100)),
                ('odd_even', models.CharField(max_length=100)),
            ],
        ),
    ]
