# Generated by Django 3.2.9 on 2021-11-14 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_schedulemodel_st_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='st_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
