# Generated by Django 3.2.9 on 2021-12-12 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_schedulemodel_au_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemodel',
            name='au_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), default=[], size=None),
        ),
    ]
