# Generated by Django 3.2.9 on 2021-12-14 18:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_schedulemodel_au_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('st_group', models.CharField(max_length=100)),
                ('odd_even', models.CharField(choices=[('even', 'чёт'), ('odd', 'нечёт')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='schedulemodel',
            name='au_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, null=True, size=None),
        ),
    ]
